### ISSUE TITLE
TDUCP install failed 

### ISSUE THREAD

**Issue by Frioo** [djey47/tdu-cp#10]
First of all, thank you for your awesome work on the game.
Unfortunately, I was unable to install your patch, tried it with admin rights, and non-admin - both fail immediately.

Here's the log:
```
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: java.lang.String.trim() is applicable for argument types: () values: []
Possible solutions: tr(java.lang.CharSequence, java.lang.CharSequence), grep(), print(java.lang.Object), print(java.io.PrintWriter), take(int), grep(java.lang.Object)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at fr.tduf.tducp.scripts.common.TDUFRunner.<init>(TDUFRunner.groovy:20)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at fr.tduf.tducp.scripts.install.Update.run(Update.groovy:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:923)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:906)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:410)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at fr.tduf.tducp.scripts.install.Update.main(Update.groovy)
```

For reference, I'm running Windows 11, and the game (TDU Gold edition) is installed on a separate hard drive.

**Comment by pmastrosimone** [comment]
+1 for this issue, same log output. Running TDU on Windows 11, also on a separate (non C:) partition.

**Comment by pmastrosimone** [comment]
Never mind, I just solved it on my own :P. Did some digging, (had a hunch it was something weird w/ Java) I have two versions of Java installed on my computer, jdk18 and jre1.8. My PC defaults to jdk18, I had edited the install.cmd to point to jre1.8 rather than the java.exe that was on my PATH and it worked immediately. Change any line that's

` java -cp `

to 

` "C:\Program Files\Java\jre1.8.0_351\bin\java" -cp ` (or whatever version/path for alternate java vers you may have) and it should work

**Comment by djey47** [comment]
Glad it worked. Have fun!

**Comment by djey47** [comment]
@Frioo any news?

**Comment by Frioo** [comment]
@djey47 I remember not getting it to work in the past. Might try it again in the nearest future with the Java thing in mind :)

**Comment by LoneNomadBlue** [comment]
I tried the solution from @pmastrosimone but changed it to my own java directory and it still didn't work. I know this is an old thread but has anyone found a solution so far?

**Comment by djey47** [comment]
> I tried the solution from @pmastrosimone but changed it to my own java directory and it still didn't work. I know this is an old thread but has anyone found a solution so far?

Are you getting the exact same error? And which directory have you used?

 It must be a java jre 1.8 (I know that's outdated but so as the project 😀). If anything useful, see this link to get a java jre (windows) https://bit.ly/2yOta0C

**Comment by LoneNomadBlue** [comment]
I have a newer version, so I guess that's the problem. Well then never mind.
